# Generated by Django 5.0.1 on 2025-12-14 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Referencia de Orden')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('customer_id_number', models.CharField(max_length=20, verbose_name='Cédula / NIT')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('shipping_address', models.TextField(verbose_name='Dirección de Envío')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('shipping_department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Pedido')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total a Pagar')),
                ('payment_method', models.CharField(choices=[('COD', 'Contraentrega'), ('WOMPI', 'Wompi - Tarjeta/PSE')], default='COD', max_length=10, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado (Aprobado)'), ('SHIPPED', 'Enviado / Despachado'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción Wompi')),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportadora')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Guía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('brand', models.CharField(choices=[('NIKE', 'Nike'), ('ADIDAS', 'Adidas'), ('PUMA', 'Puma'), ('REEBOK', 'Reebok')], max_length=50, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (COP)')),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], max_length=1, verbose_name='Género')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto de Portada')),
                ('tag', models.CharField(blank=True, help_text='Ej: Nuevo, Oferta', max_length=50, null=True, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto')),
                ('size', models.CharField(max_length=10, verbose_name='Talla')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Producto Original')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Ej: 38, 40, S, M', max_length=10, verbose_name='Talla')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Variante / Talla',
                'verbose_name_plural': 'Tallas Disponibles',
            },
        ),
    ]
