# Generated by Django 5.0.1 on 2025-12-21 03:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_brands', models.JSONField(default=list, help_text='Ejemplo: ["Nike", "Adidas", "Puma", "Reebok"]', verbose_name='Marcas Disponibles')),
                ('available_sizes', models.JSONField(default=list, help_text='Ejemplo: ["35", "36", "37", "38", "39", "40", "41", "42"]', verbose_name='Tallas Disponibles')),
                ('available_genders', models.JSONField(default=list, help_text='Ejemplo: [{"value": "M", "label": "Hombre"}, {"value": "F", "label": "Mujer"}]', verbose_name='Géneros Disponibles')),
            ],
            options={
                'verbose_name': 'Configuración de Catálogo',
                'verbose_name_plural': 'Configuración de Catálogo',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Interno')),
                ('order_code', models.CharField(editable=False, help_text='Código único para tracking (ej: VNL-A1B2C3)', max_length=15, unique=True, verbose_name='Número de Pedido')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('customer_id_number', models.CharField(max_length=20, verbose_name='Cédula / NIT')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('shipping_address', models.TextField(verbose_name='Dirección de Envío')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('shipping_department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Pedido')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo de Envío')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total a Pagar')),
                ('payment_method', models.CharField(choices=[('COD', 'Contraentrega'), ('WOMPI', 'Wompi - Tarjeta/PSE')], default='COD', max_length=10, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado (Aprobado)'), ('SHIPPED', 'Enviado / Despachado'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción Wompi')),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportadora')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Guía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('brand', models.CharField(choices=[('NIKE', 'Nike'), ('ADIDAS', 'Adidas'), ('PUMA', 'Puma'), ('REEBOK', 'Reebok')], max_length=50, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (COP)')),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], max_length=1, verbose_name='Género')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto de Portada')),
                ('tag', models.CharField(blank=True, help_text='Ej: Nuevo, Oferta', max_length=50, null=True, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrderEmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('CONFIRMATION', 'Confirmación de Compra'), ('UPDATE', 'Actualización de Estado')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to='store.order')),
            ],
            options={
                'verbose_name': 'Cola de Correo',
                'verbose_name_plural': 'Cola de Correos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto')),
                ('size', models.CharField(max_length=10, verbose_name='Talla')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Producto Original')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Producto Asociado')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost_cod', models.DecimalField(decimal_places=0, default=15000, help_text='Costo en COP. Poner 0 para envío gratis.', max_digits=10, verbose_name='Costo de Envío (Contraentrega)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, help_text='Monto mínimo de compra para envío gratis. Dejar vacío para desactivar.', max_digits=10, null=True, verbose_name='Envío gratis desde')),
                ('is_cod_enabled', models.BooleanField(default=True, verbose_name='Contraentrega Habilitado')),
                ('is_wompi_enabled', models.BooleanField(default=False, verbose_name='Wompi Habilitado')),
                ('home_highlighted_products', models.ManyToManyField(blank=True, help_text="Selecciona los productos que aparecerán en la sección 'Drops Recientes' del inicio.", related_name='highlighted_in_store_config', to='store.product', verbose_name='Productos Destacados en Home')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Ej: 38, 40, S, M', max_length=10, verbose_name='Talla')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Variante / Talla',
                'verbose_name_plural': 'Tallas Disponibles',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
