# Generated by Django 5.0.1 on 2025-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('subject', models.CharField(choices=[('GENERAL', 'Consulta general'), ('ORDER_STATUS', 'Estado de mi pedido'), ('RETURNS', 'Cambios y Devoluciones'), ('WARRANTY', 'Garantías')], max_length=20, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('READ', 'Leído'), ('REPLIED', 'Respondido'), ('CLOSED', 'Cerrado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto',
                'verbose_name_plural': 'Solicitudes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
