# Generated by Django 5.0.1 on 2025-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost_cod', models.DecimalField(decimal_places=0, default=15000, help_text='Costo en COP. Poner 0 para envío gratis.', max_digits=10, verbose_name='Costo de Envío (Contraentrega)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, help_text='Monto mínimo de compra para envío gratis. Dejar vacío para desactivar.', max_digits=10, null=True, verbose_name='Envío gratis desde')),
                ('is_cod_enabled', models.BooleanField(default=True, verbose_name='Contraentrega Habilitado')),
                ('is_wompi_enabled', models.BooleanField(default=False, verbose_name='Wompi Habilitado')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo de Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
