# Generated by Django 5.0.1 on 2025-12-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeconfig_order_shipping_cost_order_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('CONFIRMATION', 'Confirmación de Compra'), ('UPDATE', 'Actualización de Estado')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tasks', to='store.order')),
            ],
            options={
                'verbose_name': 'Cola de Correo',
                'verbose_name_plural': 'Cola de Correos',
                'ordering': ['created_at'],
            },
        ),
    ]
