# Generated by Django 5.0.1 on 2025-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderemailqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_brands', models.JSONField(default=list, help_text='Ejemplo: ["Nike", "Adidas", "Puma", "Reebok"]', verbose_name='Marcas Disponibles')),
                ('available_sizes', models.JSONField(default=list, help_text='Ejemplo: ["35", "36", "37", "38", "39", "40", "41", "42"]', verbose_name='Tallas Disponibles')),
                ('available_genders', models.JSONField(default=list, help_text='Ejemplo: [{"value": "M", "label": "Hombre"}, {"value": "F", "label": "Mujer"}]', verbose_name='Géneros Disponibles')),
            ],
            options={
                'verbose_name': 'Configuración de Catálogo',
                'verbose_name_plural': 'Configuración de Catálogo',
            },
        ),
    ]
