# Generated by Django 5.0.1 on 2025-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_catalogconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='home_highlighted_products',
            field=models.ManyToManyField(blank=True, help_text="Selecciona los productos que aparecerán en la sección 'Drops Recientes' del inicio.", related_name='highlighted_in_store_config', to='store.product', verbose_name='Productos Destacados en Home'),
        ),
    ]
