# Generated by Django 5.0.1 on 2025-12-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storeconfig_home_highlighted_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
